# These are supported funding model platforms

github:[Arminsbss] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [Arminsbss]
patreon:[Arminsbss] # Replace with a single Patreon username
open_collective:[Arminsbss] # Replace with a single Open Collective username
ko_fi:[Arminsbss] # Replace with a single Ko-fi username
tidelift:[Arminsbss] # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge:[Arminsbss] # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay:[Arminsbss] # Replace with a single Liberapay username
issuehunt:[Arminsbss] # Replace with a single IssueHunt username
otechie: #[Arminsbss] Replace with a single Otechie username
lfx_crowdfunding:[Arminsbss] # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom:['https://reymit.ir/hand-gesture-controlled-volume'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
